language: python
branches:
  only:
    - master
python:
  - "3.4"
before_install:
  - sudo apt-get install sqlite3
  - sqlite3 app/db.sqlite < init_db.sql
install:
  - pip3 install -r requirements.txt
script:
  - make test
